version: "3.7"

services:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - .docker/pg/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"